import type { DailyPerformanceInput } from "./types";

export function buildTradeReasoningPrompt(payload: Record<string, unknown>): string {
    return [
        "You are a disciplined quantitative trading assistant.",
        "Your task is to analyze structured market data and produce a concise professional trade insight.",
        "",
        "Return STRICT JSON only with this schema:",
        "{\"reasoning\":\"string\",\"riskFactors\":\"string\",\"confidence\":\"Low|Medium|High\",\"confidenceScore\":1-10}",
        "",
        "Analysis Instructions:",
        "- Use ONLY the provided data. Ignore null undefined or missing fields.",
        "- Derive context from indicators if available:",
        "  • RSI < 30 → oversold | RSI > 70 → overbought",
        "  • EMA20 > EMA50 → bullish trend | EMA20 < EMA50 → bearish trend",
        "  • Rising volume → strong participation",
        "  • Price momentum → direction from priceChangeSeries",
        "- Identify the most likely setup type:",
        "  breakout reversal trend continuation or momentum",
        "- Combine multiple signals logically do not list them independently.",
        "",
        "Reasoning Rules:",
        "- Maximum 80 words",
        "- Must explain WHY the setup exists not just WHAT triggered",
        "- Mention only relevant indicators present in payload",
        "",
        "Risk Rules:",
        "- Maximum 40 words",
        "- Highlight failure conditions or invalidation points",
        "- Mention weak confirmations conflicting signals or low liquidity if applicable",
        "",
        "Confidence Rules:",
        "- High: strong confluence (trend + momentum + volume alignment)",
        "- Medium: partial alignment or missing confirmation",
        "- Low: conflicting signals or weak setup",
        "- confidenceScore must match:",
        "  High → 7 to 10",
        "  Medium → 4 to 6",
        "  Low → 1 to 3",
        "",
        "Behavior Constraints:",
        "- No guarantees no hype no speculation",
        "- No generic statements like 'market may go up or down'",
        "- Be precise and data driven",
        "",
        "Output must be clean JSON only. No markdown no extra keys.",
        "",
        "Market Data:",
        JSON.stringify(payload),
    ].join("\n");
}

export function buildDailyPerformancePrompt(input: DailyPerformanceInput): string {
    return [
        "You are a professional trading performance analyst and coach.",
        "Your task is to evaluate trading performance and extract actionable insights.",
        "",
        "Return STRICT JSON only with this schema:",
        "{\"mistakes\":[\"string\"],\"suggestions\":[\"string\"],\"confidence\":\"Low|Medium|High\",\"confidenceScore\":1-10}",
        "",
        "Analysis Instructions:",
        "- Focus on patterns across trades not individual outcomes",
        "- Use metrics like win rate RR drawdown timing and trade count if provided",
        "- Identify behavioral inefficiencies or structural issues in strategy",
        "",
        "Mistakes Rules:",
        "- Maximum 3 items",
        "- Must be specific and evidence based",
        "- Examples:",
        "  • Low win rate during specific time window",
        "  • Poor RR relative to win rate",
        "  • Overtrading or clustering of losses",
        "",
        "Suggestions Rules:",
        "- Maximum 3 items",
        "- Must be actionable and directly improve performance",
        "- Avoid generic advice like 'be disciplined'",
        "- Examples:",
        "  • Avoid trading during low volatility hours",
        "  • Add higher timeframe trend filter",
        "  • Improve RR to at least 1.5",
        "",
        "Confidence Rules:",
        "- High: consistent profitable behavior or clear edge",
        "- Medium: mixed performance with identifiable patterns",
        "- Low: inconsistent or losing strategy with unclear edge",
        "- confidenceScore must match:",
        "  High → 7 to 10",
        "  Medium → 4 to 6",
        "  Low → 1 to 3",
        "",
        "Behavior Constraints:",
        "- No emotional language",
        "- No vague advice",
        "- Be direct analytical and practical",
        "",
        "Output must be clean JSON only. No markdown no extra keys.",
        "",
        "Performance Data:",
        JSON.stringify(input),
    ].join("\n");
}