import { Button } from "@/components/ui/button";
import type { AiStrategyBuilderResponse } from "@/types/api";
import { AI_EMPTY_STATE_EXAMPLES, AI_EMPTY_STATE_TIPS } from "./constants";

type Props = {
  result: AiStrategyBuilderResponse | null;
  onOpenInBuilder: () => void;
};

export function AiPlanReview({ result, onOpenInBuilder }: Props) {
  return (
    <div className="rounded-2xl border border-neutral-800 bg-neutral-950/70 p-5">
      <p className="text-sm font-medium text-neutral-200">Plan review</p>
      {!result ? (
        <div className="mt-3 space-y-5">
          <div className="rounded-2xl border border-neutral-800 bg-black p-4">
            <p className="text-xs uppercase tracking-[0.18em] text-[#f17463]">What happens here</p>
            <p className="mt-2 text-sm text-neutral-400">
              After generation, this panel will show the workflow summary, warnings, missing inputs, and the model used for the draft.
            </p>
            <div className="mt-4 grid gap-3 sm:grid-cols-3">
              <div className="rounded-xl border border-neutral-800 bg-neutral-950 px-3 py-3 text-xs text-neutral-400">
                Strategy summary
              </div>
              <div className="rounded-xl border border-neutral-800 bg-neutral-950 px-3 py-3 text-xs text-neutral-400">
                Risk and warning flags
              </div>
              <div className="rounded-xl border border-neutral-800 bg-neutral-950 px-3 py-3 text-xs text-neutral-400">
                Missing credentials
              </div>
            </div>
          </div>

          <div>
            <p className="text-sm font-medium text-neutral-200">Example prompts</p>
            <div className="mt-2 space-y-2">
              {AI_EMPTY_STATE_EXAMPLES.map((example) => (
                <div
                  key={example}
                  className="rounded-xl border border-neutral-800 bg-black px-3 py-3 text-sm text-neutral-400"
                >
                  {example}
                </div>
              ))}
            </div>
          </div>

          <div>
            <p className="text-sm font-medium text-neutral-200">Prompt tips</p>
            <ul className="mt-2 space-y-2 text-sm text-neutral-400">
              {AI_EMPTY_STATE_TIPS.map((tip) => (
                <li key={tip} className="rounded-xl border border-neutral-800 bg-black px-3 py-3">
                  {tip}
                </li>
              ))}
            </ul>
          </div>
        </div>
      ) : (
        <div className="space-y-5">
          <div className="mt-3 rounded-2xl border border-neutral-800 bg-black p-4">
            <p className="text-xs uppercase tracking-[0.18em] text-[#f17463]">Generated by</p>
            <p className="mt-2 text-sm text-neutral-200">
              {result.provider} / {result.model}
            </p>
            <h2 className="mt-4 text-xl font-semibold text-white">{result.plan.workflowName}</h2>
            <p className="mt-2 text-sm text-neutral-400">{result.plan.summary}</p>
            <div className="mt-4 flex flex-wrap gap-2 text-xs text-neutral-400">
              <span className="rounded-full border border-neutral-800 px-3 py-1">
                {result.plan.marketType}
              </span>
              <span className="rounded-full border border-neutral-800 px-3 py-1">
                {result.plan.nodes.length} nodes
              </span>
              <span className="rounded-full border border-neutral-800 px-3 py-1">
                {result.plan.edges.length} edges
              </span>
            </div>
          </div>

          <div>
            <p className="text-sm font-medium text-neutral-200">Warnings</p>
            <div className="mt-2 space-y-2">
              {result.plan.warnings.length === 0 ? (
                <p className="text-sm text-neutral-500">No warnings returned.</p>
              ) : (
                result.plan.warnings.map((warning) => (
                  <div
                    key={`${warning.code}-${warning.message}`}
                    className="rounded-xl border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-sm text-amber-200"
                  >
                    <span className="font-medium">{warning.code}</span>: {warning.message}
                  </div>
                ))
              )}
            </div>
          </div>

          <div>
            <p className="text-sm font-medium text-neutral-200">Missing inputs</p>
            <div className="mt-2 space-y-2">
              {result.plan.missingInputs.length === 0 ? (
                <p className="text-sm text-neutral-500">No missing inputs returned.</p>
              ) : (
                result.plan.missingInputs.map((input) => (
                  <div
                    key={`${input.nodeId}-${input.field}`}
                    className="rounded-xl border border-neutral-800 bg-black px-3 py-2 text-sm text-neutral-300"
                  >
                    <p className="font-medium text-white">{input.label}</p>
                    <p className="text-xs text-neutral-500">
                      {input.nodeType} · {input.reason}
                    </p>
                  </div>
                ))
              )}
            </div>
          </div>

          <div>
            <p className="text-sm font-medium text-neutral-200">Assumptions</p>
            <ul className="mt-2 space-y-2 text-sm text-neutral-400">
              {result.plan.assumptions.map((assumption) => (
                <li
                  key={assumption}
                  className="rounded-xl border border-neutral-800 bg-black px-3 py-2"
                >
                  {assumption}
                </li>
              ))}
            </ul>
          </div>

          <Button
            onClick={onOpenInBuilder}
            className="w-full bg-[#f17463] text-white hover:bg-[#ef826f] cursor-pointer"
          >
            Open in builder
          </Button>
        </div>
      )}
    </div>
  );
}
