export const ErrorCode = {
  BROKER_TIMEOUT: "BROKER_TIMEOUT",
  BROKER_AUTH_FAILED: "BROKER_AUTH_FAILED",
  ORDER_REJECTED: "ORDER_REJECTED",
  RATE_LIMITED: "RATE_LIMITED",
  AI_UNAVAILABLE: "AI_UNAVAILABLE",
  AI_RATE_LIMITED: "AI_RATE_LIMITED",
  AI_INVALID_RESPONSE: "AI_INVALID_RESPONSE",
  MARKET_DATA_UNAVAILABLE: "MARKET_DATA_UNAVAILABLE",
  NOTIFICATION_FAILED: "NOTIFICATION_FAILED",
  NOTIFICATION_RATE_LIMITED: "NOTIFICATION_RATE_LIMITED",
  DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
  DATABASE_QUERY_FAILED: "DATABASE_QUERY_FAILED",
  REPORTING_FAILED: "REPORTING_FAILED",
  CIRCUIT_BREAKER_OPEN: "CIRCUIT_BREAKER_OPEN",
  SOLANA_RPC_FAILED: "SOLANA_RPC_FAILED",
  SOLANA_SWAP_FAILED: "SOLANA_SWAP_FAILED",
  SOLANA_SLIPPAGE_EXCEEDED: "SOLANA_SLIPPAGE_EXCEEDED",
  SECRET_NOT_FOUND: "SECRET_NOT_FOUND",
  UNKNOWN: "UNKNOWN",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
